linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
